workflow added

diff --git a/.github/workflows/main-deploy.yaml b/.github/workflows/main-deploy.yaml
--- a/.github/workflows/main-deploy.yaml
+++ b/.github/workflows/main-deploy.yaml
@@ -1,4 +1,4 @@
-name: deploy_main
+name: deploy_to_netlify
 on:
   push:
     branches:
@@ -9,24 +9,28 @@ jobs:
     steps:
       - name: Repository Checkout
         uses: actions/checkout@v4
+
       - name: Setup NodeJS
         uses: actions/setup-node@v4
         with:
           node-version: 20
           cache: npm
-      - name: Install Netlify
-        run: npm install netlify-cli@17.10.1 -g
+
       - name: Install Dependencies
         run: npm ci
-      - name: Build project
+
+      - name: Build Project
         env:
           NUXT_PUBLIC_API_BASE_URL: ${{ secrets.NUXT_PUBLIC_API_BASE_URL }}
         run: npm run generate
+
+      - name: Validate Build
+        run: test -d dist && echo "Build directory exists" || (echo "Build failed" && exit 1)
+
       - name: Deploy to Netlify
-        id: netlify_deploy
-        run: |
-          netlify deploy \
-            --prod \
-            --dir dist \
-            --site ${{ secrets.NETLIFY_SITE_ID }} \
-            --auth ${{ secrets.NETLIFY_API_TOKEN }}
+        uses: netlify/actions@v1
+        with:
+          publish-dir: dist
+        env:
+          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
+          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
